CUDA_VISIBLE_DEVICES=0 python train_only-super_multivariate.py \
    --out_act None \
    --save_name "_dec0_lam-mse0_split-residTrue_test-orog-conv" \
    --lambda_mse_loss 0 \
    --weight_decay 0 \
    --nicolai_layers \
    --num_neighbors_res 25 \
    --mlp_depth 2 \
    --noise_dim_mlp 0 \
    --hidden_dim 12 \
    --latent_dim 12 \
    --method eng_2step \
    --variables tasmax \
    --sqrt_transform_in \
    --sqrt_transform_out \
    --num_epochs 1000 \
    --norm_method_input None \
    --norm_method_output normalise_pw \
    --kernel_size_hr 1 \
    --kernel_size_lr 2 \
    --sample_every_nepoch 100 \
    --save_model_every 100 \
    --variables_lr all \
    --batch_size 256 \
    --domain ALPS \
    --add_orography \
    --orog_conv 